# netlify.toml
[build]
  command = "npm run build"
  publish = "build"

# Environment variables
[context.production.environment]
  REACT_APP_API_URL = "https://coding-challenge-backend.onrender.com"
  NODE_ENV = "production"

# For branch deploys
[context.branch-deploy.environment]
  REACT_APP_API_URL = "https://coding-challenge-backend-staging.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
