services:
  # Backend API service
  - type: web
    name: coding-challenge-backend
    env: node
    region: oregon  # Choose a region close to your users
    plan: free  # Free tier
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /api/health
    envVars:      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true  # Automatically generate a secret
      - key: ALLOWED_ORIGINS
        value: "*"  # Allow all origins initially
      - key: MONGO_URI
        value: mongodb+srv://rohanpawar3307:XKC6s6Gr7xX9Ryzv@cluster0.0usljpu.mongodb.net/coding-challenge-db?retryWrites=true&w=majority&appName=Cluster0
      - key: NODE_ENV
        value: production
